name: first workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hello Gophers!
        run: echo "Hello fucking Gophers!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"